### ISSUE TITLE
address method missing?

### ISSUE THREAD

**Issue by mjp0** [mafintosh/utp-wasm#1]
Due platform constraint's I'm converting @hyperswarm/network to 100% JS based so I'm switching utp-native to utp-wasm but I'm running into some issues. README says that this follows same API as utp-native so I was expecting I could just drop in utp-wasm?

Mainly there's something with utp-wasm not having `this.socket.address` as a function so https://github.com/hyperswarm/network/blob/567dff3dce0dedcc9c56d57078ecf502a5bfce3e/index.js#L35 fails with `TypeError: this.socket.address is not a function`. I took a look at utp-native's code and there's a method at https://github.com/mafintosh/utp-native/blob/194a3dfd8d93567766df76563cc036a933928a6b/index.js#L77 which doesn't seem to exist in utp-wasm.

Any ideas how to fix or circumvent this?

**Comment by mafintosh** [comment]
Added in 1.1.0

**Comment by mafintosh** [comment]
Let me know if you run into any other problems
